<a href="https://colab.research.google.com/github/CVicca/BDCW/blob/main/rainfall.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

All imports, must be run first

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.cluster import KMeans
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report, confusion_matrix

Rainfall data set upload without use of Kmeans

In [ ]:
df=pd.read_csv('../Rainfall(edited final).csv')

# rainfall is classified as <1000 is light rain for the year, <1000 && >1300 is average and >1300 is heavy rain

#dataset size
print(f'The Rain table has {df.shape[0]} rows, and {df.shape[1]} columns')
df.iloc[:5, list(range(5)) + [-1]]

The Rain table has 188 rows, and 13 columns


jan    feb    mar   apr   may    ann
0  130.9   85.1  137.2  66.8  20.3   avrg
1   71.6  108.6   47.2  76.3  49.1  light
2   69.5   67.8  100.1  64.4  83.6   avrg
3   85.6   67.1   97.7  26.7  49.8   avrg
4  150.0   79.9   25.7  12.7  96.1  light

Rainfall dataset upload with use of clustering by KMeans

In [ ]:
df=pd.read_csv('../Rainfall(Kmeanstest).csv')

kmeans = KMeans(n_clusters=3, random_state=0).fit(df)

kmeans.labels_

df['ann'] = kmeans.predict(df)

print(f'The Rain table has {df.shape[0]} rows, and {df.shape[1]} columns')
df.iloc[:5, list(range(5)) + [-1]]

The Rain table has 188 rows, and 13 columns


/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


jan    feb    mar   apr   may  ann
0  130.9   85.1  137.2  66.8  20.3    1
1   71.6  108.6   47.2  76.3  49.1    2
2   69.5   67.8  100.1  64.4  83.6    1
3   85.6   67.1   97.7  26.7  49.8    1
4  150.0   79.9   25.7  12.7  96.1    2

checking the number of entries under each label

In [ ]:
df['ann'].value_counts()

2    70
1    66
0    52
Name: ann, dtype: int64

In [ ]:
X = df.iloc[:,:-1]
y = df.iloc[:,-1]
X = np.array(X)

y_labels = y
le = LabelEncoder()
le.fit(y)
y_encoded = le.transform(y)
# show few class labels after encoding
y_encoded[:10]


inversed_labels = le.inverse_transform(y_encoded)
# show few class labels after dencoding
inversed_labels[:10]

array(['avrg', 'light', 'avrg', 'avrg', 'light', 'avrg', 'light', 'light',
       'light', 'avrg'], dtype=object)

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X,y, test_size = 0.3,random_state=30)
X_train = X_train/255.0
X_test = X_test / 255.0

# create an instance of RandomForestClassifier
rf=RandomForestClassifier(n_estimators=100,)

# fit the model on training data
rf.fit(X_train,y_train)

RandomForestClassifier()

In [ ]:
# Predicted classes of the testing set
rf_predictions = rf.predict(X_test)

rf_probs = rf.predict_proba(X_test)

rf_probs[:1]

accuracy = accuracy_score(y_test, rf_predictions)
print(f'The overall accuracy of RF is {np.round(accuracy*100,2)}%')

The overall accuracy of RF is 89.47%


In [ ]:
print(confusion_matrix(y_test,rf_predictions))
print(classification_report(y_test,rf_predictions))

[[ 9  3  1]
 [ 0 23  0]
 [ 0  2 19]]
              precision    recall  f1-score   support

           0       1.00      0.69      0.82        13
           1       0.82      1.00      0.90        23
           2       0.95      0.90      0.93        21

    accuracy                           0.89        57
   macro avg       0.92      0.87      0.88        57
weighted avg       0.91      0.89      0.89        57

